require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/boat_wiring_harnesses", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # BoatWiringHarness. As you add validations to BoatWiringHarness, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      BoatWiringHarness.create! valid_attributes
      get boat_wiring_harnesses_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      boat_wiring_harness = BoatWiringHarness.create! valid_attributes
      get boat_wiring_harness_url(boat_wiring_harness)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_boat_wiring_harness_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      boat_wiring_harness = BoatWiringHarness.create! valid_attributes
      get edit_boat_wiring_harness_url(boat_wiring_harness)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new BoatWiringHarness" do
        expect {
          post boat_wiring_harnesses_url, params: { boat_wiring_harness: valid_attributes }
        }.to change(BoatWiringHarness, :count).by(1)
      end

      it "redirects to the created boat_wiring_harness" do
        post boat_wiring_harnesses_url, params: { boat_wiring_harness: valid_attributes }
        expect(response).to redirect_to(boat_wiring_harness_url(BoatWiringHarness.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new BoatWiringHarness" do
        expect {
          post boat_wiring_harnesses_url, params: { boat_wiring_harness: invalid_attributes }
        }.to change(BoatWiringHarness, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post boat_wiring_harnesses_url, params: { boat_wiring_harness: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested boat_wiring_harness" do
        boat_wiring_harness = BoatWiringHarness.create! valid_attributes
        patch boat_wiring_harness_url(boat_wiring_harness), params: { boat_wiring_harness: new_attributes }
        boat_wiring_harness.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the boat_wiring_harness" do
        boat_wiring_harness = BoatWiringHarness.create! valid_attributes
        patch boat_wiring_harness_url(boat_wiring_harness), params: { boat_wiring_harness: new_attributes }
        boat_wiring_harness.reload
        expect(response).to redirect_to(boat_wiring_harness_url(boat_wiring_harness))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        boat_wiring_harness = BoatWiringHarness.create! valid_attributes
        patch boat_wiring_harness_url(boat_wiring_harness), params: { boat_wiring_harness: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested boat_wiring_harness" do
      boat_wiring_harness = BoatWiringHarness.create! valid_attributes
      expect {
        delete boat_wiring_harness_url(boat_wiring_harness)
      }.to change(BoatWiringHarness, :count).by(-1)
    end

    it "redirects to the boat_wiring_harnesses list" do
      boat_wiring_harness = BoatWiringHarness.create! valid_attributes
      delete boat_wiring_harness_url(boat_wiring_harness)
      expect(response).to redirect_to(boat_wiring_harnesses_url)
    end
  end
end
