require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/boat_circuits", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # BoatCircuit. As you add validations to BoatCircuit, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      BoatCircuit.create! valid_attributes
      get boat_circuits_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      boat_circuit = BoatCircuit.create! valid_attributes
      get boat_circuit_url(boat_circuit)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_boat_circuit_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      boat_circuit = BoatCircuit.create! valid_attributes
      get edit_boat_circuit_url(boat_circuit)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new BoatCircuit" do
        expect {
          post boat_circuits_url, params: { boat_circuit: valid_attributes }
        }.to change(BoatCircuit, :count).by(1)
      end

      it "redirects to the created boat_circuit" do
        post boat_circuits_url, params: { boat_circuit: valid_attributes }
        expect(response).to redirect_to(boat_circuit_url(BoatCircuit.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new BoatCircuit" do
        expect {
          post boat_circuits_url, params: { boat_circuit: invalid_attributes }
        }.to change(BoatCircuit, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post boat_circuits_url, params: { boat_circuit: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested boat_circuit" do
        boat_circuit = BoatCircuit.create! valid_attributes
        patch boat_circuit_url(boat_circuit), params: { boat_circuit: new_attributes }
        boat_circuit.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the boat_circuit" do
        boat_circuit = BoatCircuit.create! valid_attributes
        patch boat_circuit_url(boat_circuit), params: { boat_circuit: new_attributes }
        boat_circuit.reload
        expect(response).to redirect_to(boat_circuit_url(boat_circuit))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        boat_circuit = BoatCircuit.create! valid_attributes
        patch boat_circuit_url(boat_circuit), params: { boat_circuit: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested boat_circuit" do
      boat_circuit = BoatCircuit.create! valid_attributes
      expect {
        delete boat_circuit_url(boat_circuit)
      }.to change(BoatCircuit, :count).by(-1)
    end

    it "redirects to the boat_circuits list" do
      boat_circuit = BoatCircuit.create! valid_attributes
      delete boat_circuit_url(boat_circuit)
      expect(response).to redirect_to(boat_circuits_url)
    end
  end
end
