require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/connector_terminals", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ConnectorTerminal. As you add validations to ConnectorTerminal, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ConnectorTerminal.create! valid_attributes
      get connector_terminals_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      connector_terminal = ConnectorTerminal.create! valid_attributes
      get connector_terminal_url(connector_terminal)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_connector_terminal_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      connector_terminal = ConnectorTerminal.create! valid_attributes
      get edit_connector_terminal_url(connector_terminal)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ConnectorTerminal" do
        expect {
          post connector_terminals_url, params: { connector_terminal: valid_attributes }
        }.to change(ConnectorTerminal, :count).by(1)
      end

      it "redirects to the created connector_terminal" do
        post connector_terminals_url, params: { connector_terminal: valid_attributes }
        expect(response).to redirect_to(connector_terminal_url(ConnectorTerminal.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ConnectorTerminal" do
        expect {
          post connector_terminals_url, params: { connector_terminal: invalid_attributes }
        }.to change(ConnectorTerminal, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post connector_terminals_url, params: { connector_terminal: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested connector_terminal" do
        connector_terminal = ConnectorTerminal.create! valid_attributes
        patch connector_terminal_url(connector_terminal), params: { connector_terminal: new_attributes }
        connector_terminal.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the connector_terminal" do
        connector_terminal = ConnectorTerminal.create! valid_attributes
        patch connector_terminal_url(connector_terminal), params: { connector_terminal: new_attributes }
        connector_terminal.reload
        expect(response).to redirect_to(connector_terminal_url(connector_terminal))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        connector_terminal = ConnectorTerminal.create! valid_attributes
        patch connector_terminal_url(connector_terminal), params: { connector_terminal: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested connector_terminal" do
      connector_terminal = ConnectorTerminal.create! valid_attributes
      expect {
        delete connector_terminal_url(connector_terminal)
      }.to change(ConnectorTerminal, :count).by(-1)
    end

    it "redirects to the connector_terminals list" do
      connector_terminal = ConnectorTerminal.create! valid_attributes
      delete connector_terminal_url(connector_terminal)
      expect(response).to redirect_to(connector_terminals_url)
    end
  end
end
