require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/splices", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Splice. As you add validations to Splice, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Splice.create! valid_attributes
      get splices_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      splice = Splice.create! valid_attributes
      get splice_url(splice)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_splice_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      splice = Splice.create! valid_attributes
      get edit_splice_url(splice)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Splice" do
        expect {
          post splices_url, params: { splice: valid_attributes }
        }.to change(Splice, :count).by(1)
      end

      it "redirects to the created splice" do
        post splices_url, params: { splice: valid_attributes }
        expect(response).to redirect_to(splice_url(Splice.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Splice" do
        expect {
          post splices_url, params: { splice: invalid_attributes }
        }.to change(Splice, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post splices_url, params: { splice: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested splice" do
        splice = Splice.create! valid_attributes
        patch splice_url(splice), params: { splice: new_attributes }
        splice.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the splice" do
        splice = Splice.create! valid_attributes
        patch splice_url(splice), params: { splice: new_attributes }
        splice.reload
        expect(response).to redirect_to(splice_url(splice))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        splice = Splice.create! valid_attributes
        patch splice_url(splice), params: { splice: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested splice" do
      splice = Splice.create! valid_attributes
      expect {
        delete splice_url(splice)
      }.to change(Splice, :count).by(-1)
    end

    it "redirects to the splices list" do
      splice = Splice.create! valid_attributes
      delete splice_url(splice)
      expect(response).to redirect_to(splices_url)
    end
  end
end
