require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/wires", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Wire. As you add validations to Wire, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Wire.create! valid_attributes
      get wires_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      wire = Wire.create! valid_attributes
      get wire_url(wire)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_wire_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      wire = Wire.create! valid_attributes
      get edit_wire_url(wire)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Wire" do
        expect {
          post wires_url, params: { wire: valid_attributes }
        }.to change(Wire, :count).by(1)
      end

      it "redirects to the created wire" do
        post wires_url, params: { wire: valid_attributes }
        expect(response).to redirect_to(wire_url(Wire.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Wire" do
        expect {
          post wires_url, params: { wire: invalid_attributes }
        }.to change(Wire, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post wires_url, params: { wire: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested wire" do
        wire = Wire.create! valid_attributes
        patch wire_url(wire), params: { wire: new_attributes }
        wire.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the wire" do
        wire = Wire.create! valid_attributes
        patch wire_url(wire), params: { wire: new_attributes }
        wire.reload
        expect(response).to redirect_to(wire_url(wire))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        wire = Wire.create! valid_attributes
        patch wire_url(wire), params: { wire: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested wire" do
      wire = Wire.create! valid_attributes
      expect {
        delete wire_url(wire)
      }.to change(Wire, :count).by(-1)
    end

    it "redirects to the wires list" do
      wire = Wire.create! valid_attributes
      delete wire_url(wire)
      expect(response).to redirect_to(wires_url)
    end
  end
end
