require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/wiring_harnesses", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # WiringHarness. As you add validations to WiringHarness, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      WiringHarness.create! valid_attributes
      get wiring_harnesses_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      wiring_harness = WiringHarness.create! valid_attributes
      get wiring_harness_url(wiring_harness)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_wiring_harness_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      wiring_harness = WiringHarness.create! valid_attributes
      get edit_wiring_harness_url(wiring_harness)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new WiringHarness" do
        expect {
          post wiring_harnesses_url, params: { wiring_harness: valid_attributes }
        }.to change(WiringHarness, :count).by(1)
      end

      it "redirects to the created wiring_harness" do
        post wiring_harnesses_url, params: { wiring_harness: valid_attributes }
        expect(response).to redirect_to(wiring_harness_url(WiringHarness.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new WiringHarness" do
        expect {
          post wiring_harnesses_url, params: { wiring_harness: invalid_attributes }
        }.to change(WiringHarness, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post wiring_harnesses_url, params: { wiring_harness: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested wiring_harness" do
        wiring_harness = WiringHarness.create! valid_attributes
        patch wiring_harness_url(wiring_harness), params: { wiring_harness: new_attributes }
        wiring_harness.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the wiring_harness" do
        wiring_harness = WiringHarness.create! valid_attributes
        patch wiring_harness_url(wiring_harness), params: { wiring_harness: new_attributes }
        wiring_harness.reload
        expect(response).to redirect_to(wiring_harness_url(wiring_harness))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        wiring_harness = WiringHarness.create! valid_attributes
        patch wiring_harness_url(wiring_harness), params: { wiring_harness: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested wiring_harness" do
      wiring_harness = WiringHarness.create! valid_attributes
      expect {
        delete wiring_harness_url(wiring_harness)
      }.to change(WiringHarness, :count).by(-1)
    end

    it "redirects to the wiring_harnesses list" do
      wiring_harness = WiringHarness.create! valid_attributes
      delete wiring_harness_url(wiring_harness)
      expect(response).to redirect_to(wiring_harnesses_url)
    end
  end
end
